version: '3'
services:
  api:
    container_name: api
    restart: always
    environment:
      DB_HOST: db
    build:
      context: .
    volumes:
      - .:/app
    command: rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

  db:
    container_name: db
    restart: always
    image: mysql:8.0.25
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: app_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_HOST: "%"
    tty: true
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password    
    ports:
      - 3306:3306